// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using KentOS.Mini.Web.Data;

#nullable disable

namespace KentOS.Mini.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250104093824_AddCommonSettingMigration")]
    partial class AddCommonSettingMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Ajanda", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<bool>("BasinKatilsin")
                        .HasColumnType("boolean")
                        .HasColumnName("basin_katilsin");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("baslik");

                    b.Property<string>("BilgiNotu")
                        .HasColumnType("text")
                        .HasColumnName("bilgi_notu");

                    b.Property<bool>("BilgiNotuDurum")
                        .HasColumnType("boolean")
                        .HasColumnName("bilgi_notu_durum");

                    b.Property<long?>("BirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("birim_id");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bitis_tarihi");

                    b.Property<long?>("CicekId")
                        .HasColumnType("bigint")
                        .HasColumnName("cicek_id");

                    b.Property<long?>("DurumId")
                        .HasColumnType("bigint")
                        .HasColumnName("durum_id");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<string>("IrtibatKisi")
                        .HasColumnType("text")
                        .HasColumnName("irtibat_kisi");

                    b.Property<string>("IrtibatTelefon")
                        .HasColumnType("text")
                        .HasColumnName("irtibat_telefon");

                    b.Property<string>("Konum")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("konum");

                    b.Property<string>("KonusmaMetni")
                        .HasColumnType("text")
                        .HasColumnName("konusma_metni");

                    b.Property<bool>("KonusmaMetniDurum")
                        .HasColumnType("boolean")
                        .HasColumnName("konusma_metni_durum");

                    b.Property<string>("Koordinat")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("koordinat");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("text")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<long>("RandevuId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_id");

                    b.Property<long?>("RandevuTipId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_tip_id");

                    b.Property<bool>("ResimVar")
                        .HasColumnType("boolean")
                        .HasColumnName("resim_var");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<bool>("TekrarEden")
                        .HasColumnType("boolean")
                        .HasColumnName("tekrar_eden");

                    b.Property<bool>("TumGun")
                        .HasColumnType("boolean")
                        .HasColumnName("tum_gun");

                    b.HasKey("Id")
                        .HasName("pk_ajandalar");

                    b.HasIndex("BirimId")
                        .HasDatabaseName("ix_ajandalar_birim_id");

                    b.HasIndex("DurumId")
                        .HasDatabaseName("ix_ajandalar_durum_id");

                    b.HasIndex("RandevuTipId")
                        .HasDatabaseName("ix_ajandalar_randevu_tip_id");

                    b.ToTable("ajandalar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaDurum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("icon");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("renk");

                    b.HasKey("Id")
                        .HasName("pk_ajanda_durumlar");

                    b.ToTable("ajanda_durumlar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<bool>("AsagiHareket")
                        .HasColumnType("boolean")
                        .HasColumnName("asagi_hareket");

                    b.Property<string>("EskiBirim")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("eski_birim");

                    b.Property<long>("EskiBirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("eski_birim_id");

                    b.Property<string>("Kullanici")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("kullanici");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tarih");

                    b.Property<string>("YeniBirim")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yeni_birim");

                    b.Property<long>("YeniBirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("yeni_birim_id");

                    b.HasKey("Id")
                        .HasName("pk_ajanda_hareketler");

                    b.HasIndex("AjandaId")
                        .HasDatabaseName("ix_ajanda_hareketler_ajanda_id");

                    b.ToTable("ajanda_hareketler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaNot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long?>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("not");

                    b.Property<string>("Olusturan")
                        .HasColumnType("text")
                        .HasColumnName("olusturan");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_tarihi");

                    b.HasKey("Id")
                        .HasName("pk_ajanda_notlar");

                    b.HasIndex("AjandaId")
                        .HasDatabaseName("ix_ajanda_notlar_ajanda_id");

                    b.ToTable("ajanda_notlar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaPhoto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<long>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.HasKey("Id")
                        .HasName("pk_ajanda_photos");

                    b.HasIndex("AjandaId")
                        .HasDatabaseName("ix_ajanda_photos_ajanda_id");

                    b.ToTable("ajanda_photos", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaTekrar", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<string>("AyinGunleri")
                        .HasColumnType("text")
                        .HasColumnName("ayin_gunleri");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("baslangic_tarihi");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bitis_tarihi");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<int?>("HaftaninGunleri")
                        .HasColumnType("integer")
                        .HasColumnName("haftanin_gunleri");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturma_tarihi");

                    b.Property<int?>("TekrarSayisi")
                        .HasColumnType("integer")
                        .HasColumnName("tekrar_sayisi");

                    b.Property<int>("TekrarSikligi")
                        .HasColumnType("integer")
                        .HasColumnName("tekrar_sikligi");

                    b.HasKey("Id")
                        .HasName("pk_ajanda_tekrarlar");

                    b.HasIndex("AjandaId")
                        .HasDatabaseName("ix_ajanda_tekrarlar_ajanda_id");

                    b.ToTable("ajanda_tekrarlar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AppRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AppUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("Ad")
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<long?>("BirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("birim_id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("FcmToken")
                        .HasColumnType("text")
                        .HasColumnName("fcm_token");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Soyad")
                        .HasColumnType("text")
                        .HasColumnName("soyad");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("Unvan")
                        .HasColumnType("text")
                        .HasColumnName("unvan");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("BirimId")
                        .HasDatabaseName("ix_asp_net_users_birim_id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Birim", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int>("LeftId")
                        .HasColumnType("integer")
                        .HasColumnName("left_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("RightId")
                        .HasColumnType("integer")
                        .HasColumnName("right_id");

                    b.Property<string>("Telefon")
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.Property<string>("Unvan")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("unvan");

                    b.Property<long?>("UstBirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("ust_birim_id");

                    b.Property<string>("Yetkili")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yetkili");

                    b.HasKey("Id")
                        .HasName("pk_birimler");

                    b.HasIndex("UstBirimId")
                        .HasDatabaseName("ix_birimler_ust_birim_id");

                    b.ToTable("birimler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Cicek", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<long?>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<long>("CicekciId")
                        .HasColumnType("bigint")
                        .HasColumnName("cicekci_id");

                    b.Property<int>("DogrulamaKodu")
                        .HasColumnType("integer")
                        .HasColumnName("dogrulama_kodu");

                    b.Property<bool>("Gonderildi")
                        .HasColumnType("boolean")
                        .HasColumnName("gonderildi");

                    b.Property<DateTime>("GonderilmeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("gonderilme_tarihi");

                    b.Property<string>("Guid")
                        .HasColumnType("text")
                        .HasColumnName("guid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_tarihi");

                    b.Property<string>("Olusturan")
                        .HasColumnType("text")
                        .HasColumnName("olusturan");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturulma_tarihi");

                    b.Property<string>("Resim")
                        .HasColumnType("text")
                        .HasColumnName("resim");

                    b.HasKey("Id")
                        .HasName("pk_cicekler");

                    b.HasIndex("AjandaId")
                        .IsUnique()
                        .HasDatabaseName("ix_cicekler_ajanda_id");

                    b.HasIndex("CicekciId")
                        .HasDatabaseName("ix_cicekler_cicekci_id");

                    b.ToTable("cicekler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Cicekci", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad_soyad");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("adres");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean")
                        .HasColumnName("aktif");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefon");

                    b.HasKey("Id")
                        .HasName("pk_cicekciler");

                    b.ToTable("cicekciler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Mahalle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.HasKey("Id")
                        .HasName("pk_mahalleler");

                    b.ToTable("mahalleler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Meslek", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.HasKey("Id")
                        .HasName("pk_meslekler");

                    b.ToTable("meslekler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Data")
                        .HasColumnType("text")
                        .HasColumnName("data");

                    b.Property<string>("FailMessage")
                        .HasColumnType("text")
                        .HasColumnName("fail_message");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean")
                        .HasColumnName("is_success");

                    b.Property<int>("MessageType")
                        .HasColumnType("integer")
                        .HasColumnName("message_type");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages");

                    b.ToTable("messages", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Oneri", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("baslik");

                    b.Property<string>("Cevap")
                        .HasColumnType("text")
                        .HasColumnName("cevap");

                    b.Property<DateTime?>("CevapTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("cevap_tarih");

                    b.Property<string>("KullaniciAdi")
                        .HasColumnType("text")
                        .HasColumnName("kullanici_adi");

                    b.Property<long?>("KullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tarih");

                    b.Property<int>("Tip")
                        .HasColumnType("integer")
                        .HasColumnName("tip");

                    b.HasKey("Id")
                        .HasName("pk_oneriler");

                    b.ToTable("oneriler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Randevu", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("ad");

                    b.Property<string>("Adres")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("adres");

                    b.Property<bool>("AjandaDurum")
                        .HasColumnType("boolean")
                        .HasColumnName("ajanda_durum");

                    b.Property<long>("AjandaId")
                        .HasColumnType("bigint")
                        .HasColumnName("ajanda_id");

                    b.Property<bool>("Arsivlendi")
                        .HasColumnType("boolean")
                        .HasColumnName("arsivlendi");

                    b.Property<DateTime>("BaslangicTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("baslangic_tarih");

                    b.Property<long?>("BirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("birim_id");

                    b.Property<DateTime>("BitisTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("bitis_tarih");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<DateTime?>("GuncellemeTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("guncelleme_tarih");

                    b.Property<string>("Guncelleyen")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("guncelleyen");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("konu");

                    b.Property<string>("Koordinat")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("koordinat");

                    b.Property<long>("MahalleId")
                        .HasColumnType("bigint")
                        .HasColumnName("mahalle_id");

                    b.Property<string>("Meslek")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("meslek");

                    b.Property<string>("Olusturan")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("olusturan");

                    b.Property<DateTime?>("OlusturmaTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturma_tarih");

                    b.Property<string>("OzgecmisDosya")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ozgecmis_dosya");

                    b.Property<bool>("OzgecmisDurum")
                        .HasColumnType("boolean")
                        .HasColumnName("ozgecmis_durum");

                    b.Property<long>("RandevuDurumId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_durum_id");

                    b.Property<long?>("RandevuTipId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_tip_id");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("soyad");

                    b.Property<DateTime?>("TamamlanmaTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tamamlanma_tarih");

                    b.Property<string>("Telefon")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("telefon");

                    b.Property<string>("Yer")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yer");

                    b.HasKey("Id")
                        .HasName("pk_randevular");

                    b.HasIndex("BaslangicTarih")
                        .HasDatabaseName("ix_randevular_baslangic_tarih");

                    b.HasIndex("BirimId")
                        .HasDatabaseName("ix_randevular_birim_id");

                    b.HasIndex("BitisTarih")
                        .HasDatabaseName("ix_randevular_bitis_tarih");

                    b.HasIndex("MahalleId")
                        .HasDatabaseName("ix_randevular_mahalle_id");

                    b.HasIndex("RandevuDurumId")
                        .HasDatabaseName("ix_randevular_randevu_durum_id");

                    b.HasIndex("RandevuTipId")
                        .HasDatabaseName("ix_randevular_randevu_tip_id");

                    b.HasIndex("Ad", "Soyad", "Meslek", "Email", "Telefon")
                        .HasDatabaseName("ix_randevular_ad_soyad_meslek_email_telefon");

                    b.ToTable("randevular", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuDosya", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ad");

                    b.Property<string>("ContentType")
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTime?>("OlusturmaTarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("olusturma_tarih");

                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<long?>("RandevuId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_id");

                    b.Property<long?>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.HasKey("Id")
                        .HasName("pk_dosyalar");

                    b.HasIndex("RandevuId")
                        .HasDatabaseName("ix_dosyalar_randevu_id");

                    b.ToTable("dosyalar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuDurum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("aciklama");

                    b.Property<string>("DurumAd")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("durum_ad");

                    b.Property<string>("Renk")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("renk");

                    b.Property<string>("Simge")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("simge");

                    b.HasKey("Id")
                        .HasName("pk_randevu_durumlar");

                    b.ToTable("randevu_durumlar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuHareket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<bool>("AsagiHareket")
                        .HasColumnType("boolean")
                        .HasColumnName("asagi_hareket");

                    b.Property<string>("EskiBirim")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("eski_birim");

                    b.Property<long>("EskiBirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("eski_birim_id");

                    b.Property<string>("Kullanici")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("kullanici");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("bigint")
                        .HasColumnName("kullanici_id");

                    b.Property<long>("RandevuId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_id");

                    b.Property<string>("Tarih")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("tarih");

                    b.Property<string>("YeniBirim")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("yeni_birim");

                    b.Property<long>("YeniBirimId")
                        .HasColumnType("bigint")
                        .HasColumnName("yeni_birim_id");

                    b.HasKey("Id")
                        .HasName("pk_randevu_hareketler");

                    b.HasIndex("EskiBirimId")
                        .HasDatabaseName("ix_randevu_hareketler_eski_birim_id");

                    b.HasIndex("KullaniciId")
                        .HasDatabaseName("ix_randevu_hareketler_kullanici_id");

                    b.HasIndex("RandevuId")
                        .HasDatabaseName("ix_randevu_hareketler_randevu_id");

                    b.HasIndex("YeniBirimId")
                        .HasDatabaseName("ix_randevu_hareketler_yeni_birim_id");

                    b.ToTable("randevu_hareketler", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuNot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Not")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("not");

                    b.Property<string>("Olusturan")
                        .HasColumnType("text")
                        .HasColumnName("olusturan");

                    b.Property<long?>("RandevuId")
                        .HasColumnType("bigint")
                        .HasColumnName("randevu_id");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("tarih");

                    b.Property<string>("Tip")
                        .HasColumnType("text")
                        .HasColumnName("tip");

                    b.HasKey("Id")
                        .HasName("pk_notlar");

                    b.HasIndex("RandevuId")
                        .HasDatabaseName("ix_notlar_randevu_id");

                    b.ToTable("notlar", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuTip", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("aciklama");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ad");

                    b.Property<string>("Renk")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("renk");

                    b.HasKey("Id")
                        .HasName("pk_randevu_tipleri");

                    b.ToTable("randevu_tipleri", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Sibeski.IcmesuyuAnaliz", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text")
                        .HasColumnName("aciklama");

                    b.Property<float?>("Alkalinite")
                        .HasColumnType("real")
                        .HasColumnName("alkalinite");

                    b.Property<float?>("Amonyak")
                        .HasColumnType("real")
                        .HasColumnName("amonyak");

                    b.Property<Guid>("AnalizNo")
                        .HasColumnType("uuid")
                        .HasColumnName("analiz_no");

                    b.Property<int>("AnalizNokta")
                        .HasColumnType("integer")
                        .HasColumnName("analiz_nokta");

                    b.Property<float?>("Bakteriyolojik")
                        .HasColumnType("real")
                        .HasColumnName("bakteriyolojik");

                    b.Property<float?>("Bulaniklik")
                        .HasColumnType("real")
                        .HasColumnName("bulaniklik");

                    b.Property<float?>("Casertlik")
                        .HasColumnType("real")
                        .HasColumnName("casertlik");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<float?>("Demir")
                        .HasColumnType("real")
                        .HasColumnName("demir");

                    b.Property<float?>("Iletkenlik")
                        .HasColumnType("real")
                        .HasColumnName("iletkenlik");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("text")
                        .HasColumnName("last_modified_by");

                    b.Property<float?>("Mangan")
                        .HasColumnType("real")
                        .HasColumnName("mangan");

                    b.Property<float?>("Mgsertlik")
                        .HasColumnType("real")
                        .HasColumnName("mgsertlik");

                    b.Property<float?>("Nitrat")
                        .HasColumnType("real")
                        .HasColumnName("nitrat");

                    b.Property<float?>("Nitrit")
                        .HasColumnType("real")
                        .HasColumnName("nitrit");

                    b.Property<float?>("Oksijen")
                        .HasColumnType("real")
                        .HasColumnName("oksijen");

                    b.Property<float?>("Permanganat")
                        .HasColumnType("real")
                        .HasColumnName("permanganat");

                    b.Property<float?>("Ph")
                        .HasColumnType("real")
                        .HasColumnName("ph");

                    b.Property<float?>("Phs")
                        .HasColumnType("real")
                        .HasColumnName("phs");

                    b.Property<float?>("Renk")
                        .HasColumnType("real")
                        .HasColumnName("renk");

                    b.Property<float?>("SerbestKlor")
                        .HasColumnType("real")
                        .HasColumnName("serbest_klor");

                    b.Property<float?>("Sicaklik")
                        .HasColumnType("real")
                        .HasColumnName("sicaklik");

                    b.Property<DateOnly>("Tarih")
                        .HasColumnType("date")
                        .HasColumnName("tarih");

                    b.Property<float?>("Tds")
                        .HasColumnType("real")
                        .HasColumnName("tds");

                    b.Property<float?>("Tsertlik")
                        .HasColumnType("real")
                        .HasColumnName("tsertlik");

                    b.Property<DateTime?>("Updated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_icmesuyu_analizleri");

                    b.ToTable("icmesuyu_analizleri", (string)null);
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.UserSetting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("Id"));

                    b.Property<bool>("AgendaOnCreated")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_created");

                    b.Property<bool>("AgendaOnDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_deleted");

                    b.Property<bool>("AgendaOnFlowerDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_flower_deleted");

                    b.Property<bool>("AgendaOnFlowerSent")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_flower_sent");

                    b.Property<bool>("AgendaOnImageUpload")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_image_upload");

                    b.Property<bool>("AgendaOnNoteAdded")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_note_added");

                    b.Property<bool>("AgendaOnOrganized")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_organized");

                    b.Property<bool>("AgendaOnPostponed")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_postponed");

                    b.Property<bool>("AgendaOnStatusChange")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_status_change");

                    b.Property<bool>("AgendaOnUpdated")
                        .HasColumnType("boolean")
                        .HasColumnName("agenda_on_updated");

                    b.Property<bool>("HideOldAgendas")
                        .HasColumnType("boolean")
                        .HasColumnName("hide_old_agendas");

                    b.Property<bool>("RequestOnAddedToAgenda")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_added_to_agenda");

                    b.Property<bool>("RequestOnCreated")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_created");

                    b.Property<bool>("RequestOnDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_deleted");

                    b.Property<bool>("RequestOnFileAttached")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_file_attached");

                    b.Property<bool>("RequestOnNoteAdded")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_note_added");

                    b.Property<bool>("RequestOnOrganized")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_organized");

                    b.Property<bool>("RequestOnRemittance")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_remittance");

                    b.Property<bool>("RequestOnStatusChange")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_status_change");

                    b.Property<bool>("RequestOnUpdated")
                        .HasColumnType("boolean")
                        .HasColumnName("request_on_updated");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_settings");

                    b.ToTable("user_settings", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("KentOS.Mini.Application.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Ajanda", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Birim", "Birim")
                        .WithMany("Ajandalar")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ajandalar_birimler_birim_id");

                    b.HasOne("KentOS.Mini.Application.Models.AjandaDurum", "Durum")
                        .WithMany("Ajandalar")
                        .HasForeignKey("DurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ajandalar_ajanda_durumlar_durum_id");

                    b.HasOne("KentOS.Mini.Application.Models.RandevuTip", "RandevuTip")
                        .WithMany("Ajandalar")
                        .HasForeignKey("RandevuTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ajandalar_randevu_tipleri_randevu_tip_id");

                    b.Navigation("Birim");

                    b.Navigation("Durum");

                    b.Navigation("RandevuTip");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaHareket", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", "Ajanda")
                        .WithMany()
                        .HasForeignKey("AjandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ajanda_hareketler_ajandalar_ajanda_id");

                    b.Navigation("Ajanda");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaNot", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", "Ajanda")
                        .WithMany("AjandaNotlar")
                        .HasForeignKey("AjandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ajanda_notlar_ajandalar_ajanda_id");

                    b.Navigation("Ajanda");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaPhoto", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", "Ajanda")
                        .WithMany("Photos")
                        .HasForeignKey("AjandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ajanda_photos_ajandalar_ajanda_id");

                    b.Navigation("Ajanda");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaTekrar", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", "Ajanda")
                        .WithMany()
                        .HasForeignKey("AjandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ajanda_tekrarlar_ajandalar_ajanda_id");

                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", null)
                        .WithOne("TekrarDetaylari")
                        .HasForeignKey("KentOS.Mini.Application.Models.AjandaTekrar", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_ajanda_tekrarlar_ajandalar_id");

                    b.Navigation("Ajanda");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AppUser", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .HasConstraintName("fk_asp_net_users_birimler_birim_id");

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Birim", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Birim", "UstBirim")
                        .WithMany("AltBirimler")
                        .HasForeignKey("UstBirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_birimler_birimler_ust_birim_id");

                    b.Navigation("UstBirim");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Cicek", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Ajanda", "Ajanda")
                        .WithOne("Cicek")
                        .HasForeignKey("KentOS.Mini.Application.Models.Cicek", "AjandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_cicekler_ajandalar_ajanda_id");

                    b.Navigation("Ajanda");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Randevu", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Birim", "Birim")
                        .WithMany("Randevular")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_randevular_birimler_birim_id");

                    b.HasOne("KentOS.Mini.Application.Models.Mahalle", "Mahalle")
                        .WithMany("Randevular")
                        .HasForeignKey("MahalleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_randevular_mahalleler_mahalle_id");

                    b.HasOne("KentOS.Mini.Application.Models.RandevuDurum", "RandevuDurum")
                        .WithMany("Randevular")
                        .HasForeignKey("RandevuDurumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_randevular_randevu_durumlar_randevu_durum_id");

                    b.HasOne("KentOS.Mini.Application.Models.RandevuTip", "RandevuTip")
                        .WithMany("Randevular")
                        .HasForeignKey("RandevuTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_randevular_randevu_tipleri_randevu_tip_id");

                    b.Navigation("Birim");

                    b.Navigation("Mahalle");

                    b.Navigation("RandevuDurum");

                    b.Navigation("RandevuTip");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuDosya", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Randevu", "Randevu")
                        .WithMany("Dosyalar")
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_dosyalar_randevular_randevu_id");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuHareket", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Randevu", "Randevu")
                        .WithMany("Hareketler")
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_randevu_hareketler_randevular_randevu_id");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuNot", b =>
                {
                    b.HasOne("KentOS.Mini.Application.Models.Randevu", "Randevu")
                        .WithMany("Notlar")
                        .HasForeignKey("RandevuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_notlar_randevular_randevu_id");

                    b.Navigation("Randevu");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Ajanda", b =>
                {
                    b.Navigation("AjandaNotlar");

                    b.Navigation("Cicek");

                    b.Navigation("Photos");

                    b.Navigation("TekrarDetaylari");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.AjandaDurum", b =>
                {
                    b.Navigation("Ajandalar");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Birim", b =>
                {
                    b.Navigation("Ajandalar");

                    b.Navigation("AltBirimler");

                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Mahalle", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.Randevu", b =>
                {
                    b.Navigation("Dosyalar");

                    b.Navigation("Hareketler");

                    b.Navigation("Notlar");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuDurum", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("KentOS.Mini.Application.Models.RandevuTip", b =>
                {
                    b.Navigation("Ajandalar");

                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
